FROM openjdk:17-alpine
ARG JAR_PATH=/build/libs/*.jar
COPY ${JAR_PATH} /home/server.jar
ENTRYPOINT ["java","-jar","/home/server.jar"]
ARG OPEN_AI_KEY
ARG OPEN_API_KEY
ENV OPEN_API_KEY=${OPEN_API_KEY}
ENV OPEN_AI_KEY=${OPEN_AI_KEY}
ARG SPRING_DATASOURCE_HOST
ARG SPRING_DATASOURCE_PASSWORD
ARG SPRING_DATASOURCE_USERNAME
ENV SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
ENV SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
ENV SPRING_DATASOURCE_HOST=${SPRING_DATASOURCE_HOST}
